Send erros to jitsu
deco-cx/live pull request #86
Opened 2023-01-19 22:33 UTC by soutofernando

2023-01-19 22:48 UTC, lucis requested changes

2023-01-19 22:48 UTC, lucis commented on components/LiveAnalytics.tsx
> +const IS_TESTING_JITSU = true;
Remove

2023-01-19 22:48 UTC, lucis commented on components/LiveAnalytics.tsx
> +`;
Better formatting

2023-01-19 22:48 UTC, lucis commented on components/LiveAnalytics.tsx
> +
Remove

2023-01-20 12:25 UTC, igorbrasileiro commented on components/LiveAnalytics.tsx
> +  window.onerror = function (message, url, lineNo, columnNo, error) {
What do you think about adding an event listener to the error event handler, something like this:
```js
window.addEventListener('error', function (...) {...}})
```

2023-01-20 12:27 UTC, igorbrasileiro approved these changes

2023-01-24 14:18 UTC, merged